### ISSUE TITLE
Animation Freeze

### ISSUE THREAD

**Issue by ahmedaomda** [jfoenixadmin/JFoenix#816] opened 2018-08-27 12:04 UTC
when clicking JFXButton to change the scene the click animation freezes for half a second then switch without completing the animation is that a bug or there is away to wait till the animation finish ?

**Comment by jfoenixadmin** [comment] 2018-08-28 07:34
try to run your action in a different thread instead of fx-thread

**Comment by ahmedaomda** [comment] 2018-08-28 09:41
I used Platform.runLater() as I'm changing the content of the scene but it doesn't help much

**Comment by ricard-v** [comment] 2018-08-28 10:31
@ahmedaomda the method `Platform.runLater(Runnable r)` is slightly ambiguous because of its name, but the document is quite explicit: 

> Run the specified Runnable on the JavaFX Application Thread at some unspecified time in the future. [...]

So it is highly possible that the code that changes the scene content is being executed while the click animation takes place.
Usually, you should execute the scene changes inside the FX application (UI) thread. But maybe the content is heavy and you do a lot of business logic that is not necessarily UI related ?
I believe you may use the FXMLoader on a worker thread but its result must be executed on UI thread.

All in all, you should keep the FX application thread as idle as possible to keep the UI butter smooth.

**Comment by ahmedaomda** [comment] 2018-08-28 10:45
Thanks for your replay but I didn't make any business logic yet it's just the UI and the UI loaded is so simple just VBox  that contain textfields and empty listview and buttons nothing fancy

**Comment by ricard-v** [comment] 2018-08-28 13:48
@ahmedaomda Your welcome 👍 

Without code it will be hard to understand if there are any heavy-lifting. Unless the animation itself is buggy (which I do not sincerely believe), there must be something happening on the UI thread to cause the freezes.
If you can share the code involved in the UI operation starting from the button click to the transition of the scene, maybe something interesting can be spotted.

Finally, as a (ugly) workaround, yes you might wait for the animation to finish. To be more precise, you may delay the button action (using a Timer, for example) for as long as the animation lasts. However, I do not know how long it lasts. On another issue, I saw that the `JFXRippler` lasts 500ms. #773.
So try to delay your button action by 500 milliseconds and see if the animation has _time_ to run smoothly. That would be an ugly workaround since it would no solve the cause of the jankiness of your animation.

Good luck !

**Comment by jfoenixadmin** [comment] 2018-09-10 09:11
will close this issue since @ahmedaomda  didn't reply

**Closed by jfoenixadmin** 2018-09-10 09:11 UTC

**Comment by schlegel11** [comment] 2018-09-14 21:03
@ricard-v 
I have to mention that the 500ms was my changed value in the other issue. The default value is 900ms.
