### ISSUE TITLE
Hamburger error ?

### ISSUE THREAD

**Issue by bangjohn** [jfoenixadmin/JFoenix#317] opened 2017-05-07 16:12 UTC
can you help me why this is happen ?
thanks

![animation1](https://cloud.githubusercontent.com/assets/19603309/25782741/93c7c0ac-337a-11e7-9e3b-95e75af21cb8.gif)
![screenshot_70](https://cloud.githubusercontent.com/assets/19603309/25782742/9e2fbc5c-337a-11e7-92e9-853e489c0669.png)

**Comment by jfoenixadmin** [comment] 2017-05-08 06:21
Hello, 
can you provide a sample code demonstrating the issue, as we were not able to reproduce.

Regards,

**Comment by bangjohn** [comment] 2017-05-08 15:33
``package AplikasiPerpustakaan;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;
import com.jfoenix.controls.JFXTextField;
import com.jfoenix.transitions.hamburger.HamburgerBackArrowBasicTransition;
import com.jfoenix.transitions.hamburger.HamburgerBasicCloseTransition;
import com.jfoenix.transitions.hamburger.HamburgerNextArrowBasicTransition;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;


public class Controller {

    @FXML
    private AnchorPane anchorpanedatabuku;

    @FXML
    private JFXDrawer menusamping;

    @FXML
    private JFXHamburger hamburgermenu;

    public void masukadmin(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/login-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Login Admin");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void masukmahasiswa(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/mahasiswa/login-mahasiswa.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void halamanlogin(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/main.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }


    // Kontrol Admin
    //=============================================================================================================
    public void pilihdatabukuadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/databuku-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Data Buku");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void pilihdatamahasiswaadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/datamahasiswa-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Data Mahasiswa");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void pilihtambahdatabukuadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/tambahbuku-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Tambah Data Buku");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    // Data Buku Admin Controller
    // ===================================================================================
    public void fungsimenuhamburger(MouseEvent mouseEvent) throws Exception{
        HamburgerBasicCloseTransition menuhamburger = new HamburgerBasicCloseTransition(hamburgermenu);
        menuhamburger.setRate(-1);
        hamburgermenu.addEventHandler(MouseEvent.MOUSE_PRESSED, (event -> {
            menuhamburger.setRate(menuhamburger.getRate()*-1);
            menuhamburger.play();

            if(menusamping.isShown())
                menusamping.close();
            else
                menusamping.open();
        }));
    }


}

**Comment by bangjohn** [comment] 2017-05-08 15:34
package AplikasiPerpustakaan;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;
import com.jfoenix.controls.JFXTextField;
import com.jfoenix.transitions.hamburger.HamburgerBackArrowBasicTransition;
import com.jfoenix.transitions.hamburger.HamburgerBasicCloseTransition;
import com.jfoenix.transitions.hamburger.HamburgerNextArrowBasicTransition;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;


public class Controller {

    @FXML
    private AnchorPane anchorpanedatabuku;

    @FXML
    private JFXDrawer menusamping;

    @FXML
    private JFXHamburger hamburgermenu;

    public void masukadmin(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/login-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Login Admin");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void masukmahasiswa(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/mahasiswa/login-mahasiswa.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void halamanlogin(ActionEvent event) throws Exception {
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/main.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }


    // Kontrol Admin
    //=============================================================================================================
    public void pilihdatabukuadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/databuku-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Data Buku");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void pilihdatamahasiswaadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/datamahasiswa-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Data Mahasiswa");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    public void pilihtambahdatabukuadmin(ActionEvent event) throws Exception{
        Stage menudaftarbaru = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("fxml/admin/tambahbuku-admin.fxml"));
        Scene scene = new Scene(root);
        menudaftarbaru.setTitle("Aplikasi Perpustakaan - Tambah Data Buku");
        menudaftarbaru.setScene(scene);
        menudaftarbaru.resizableProperty().setValue(Boolean.FALSE);
        menudaftarbaru.show();
        ((Node)(event.getSource())).getScene().getWindow().hide();
    }

    // Data Buku Admin Controller
    // ===================================================================================
    public void fungsimenuhamburger(MouseEvent mouseEvent) throws Exception{
        HamburgerBasicCloseTransition menuhamburger = new HamburgerBasicCloseTransition(hamburgermenu);
        menuhamburger.setRate(-1);
        hamburgermenu.addEventHandler(MouseEvent.MOUSE_PRESSED, (event -> {
            menuhamburger.setRate(menuhamburger.getRate()*-1);
            menuhamburger.play();

            if(menusamping.isShown())
                menusamping.close();
            else
                menusamping.open();
        }));
    }


}

**Comment by bangjohn** [comment] 2017-05-08 15:34
``<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXButton?>
<?import com.jfoenix.controls.JFXDrawer?>
<?import com.jfoenix.controls.JFXHamburger?>
<?import com.jfoenix.controls.JFXTreeTableView?>
<?import javafx.scene.control.TextField?>
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.layout.Pane?>
<?import javafx.scene.shape.Line?>
<?import javafx.scene.text.Font?>
<?import javafx.scene.text.Text?>

<AnchorPane fx:id="anchorpanedatabuku" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="480.0" prefWidth="848.0" xmlns="http://javafx.com/javafx/8.0.60" xmlns:fx="http://javafx.com/fxml/1" fx:controller="AplikasiPerpustakaan.Controller">
   <children>
      <Pane layoutY="-4.0" prefHeight="27.0" prefWidth="861.0" style="-fx-background-color: #800000;" />
      <Pane layoutX="-2.0" layoutY="23.0" prefHeight="13.0" prefWidth="861.0" style="-fx-background-color: #a6a6a6;" />
      <Text layoutX="5.0" layoutY="58.0" strokeType="OUTSIDE" strokeWidth="0.0" text="Data Buku" wrappingWidth="129.50976648181677">
         <font>
            <Font size="20.0" />
         </font>
      </Text>
      <Line endX="50.0" layoutX="107.0" layoutY="68.0" startX="-100.0" strokeMiterLimit="0.0" />
      <TextField layoutX="5.0" layoutY="79.0" prefHeight="25.0" prefWidth="716.0" promptText="Masukan nama buku" />
      <JFXButton buttonType="RAISED" layoutX="727.0" layoutY="79.0" prefHeight="25.0" prefWidth="115.0" ripplerFill="WHITE" style="-fx-background-color: #800000;" text="Cari" textFill="WHITE" />
      <JFXTreeTableView layoutX="5.0" layoutY="107.0" prefHeight="365.0" prefWidth="840.0" />
      <JFXHamburger fx:id="hamburgermenu" layoutX="797.0" layoutY="37.0" onMousePressed="#fungsimenuhamburger" prefHeight="34.0" prefWidth="45.0" />
      <JFXDrawer fx:id="menusamping" defaultDrawerSize="190.0" prefHeight="482.0" prefWidth="155.0" />
   </children>
</AnchorPane>

**Comment by jfoenixadmin** [comment] 2017-05-09 06:39
it's not clear how and where you are using the method `fungsimenuhamburger` / how the `hamburgermenu `object was built in fxml. please provide more info in order to be able to reproduce the issue.

**Comment by jfoenixadmin** [comment] 2017-05-10 06:22
Hello, 
well you added the mouse Pressed handler in FXML, and you readded it again in the code ( which is wrong ) your method `fungsimenuhamburger `should be as the following :

```
menuhamburger.setRate(menuhamburger.getRate()*-1);
menuhamburger.play();
if(menusamping.isShown())
    menusamping.close();
else
    menusamping.open();
```
Creating the transition and setting the initial rate should be outside the MouseEvent Handler.
This issue will be closed as it's not related to JFoenix development.
Regards,

**Closed by jfoenixadmin** 2017-05-10 06:22 UTC
