### ISSUE TITLE
JFXMasonryPane positions children over each other sometimes

### ISSUE THREAD

**Issue by xwavex** [jfoenixadmin/JFoenix#474] opened 2017-10-25 10:21 UTC
When I add new children to a JFXMasonryPane, it sometimes happens that multiple children are positioned on the same spot. (BTW I am using D'n'D to add children, but since I just call masonryPane.getChildren.add(...) it shouldn't be an issue I guess).
In the image below you can see that one object is overlapping with another one (black/bold text) and one is just floating in the middle of the masonry area in the bottom left corner.
Any ideas?

![githubmasonryissue](https://user-images.githubusercontent.com/7841720/31993723-681dac3e-b97e-11e7-9833-072a0b797694.png)

**Comment by jfoenixadmin** [comment] 2017-10-25 20:08
Hello,
well if you can provide a sample code to demonstrate the issue it would be appreciated. it's not clear how to reproduce.

Regards,

**Comment by jfoenixadmin** [comment] 2017-12-07 14:33
Will close this issue, as we were not able to reproduce and you didn't provide more details about it.

**Closed by jfoenixadmin** 2017-12-07 14:33 UTC

**Comment by cyberpwnn** [comment] 2018-08-20 05:12
Its the listener on the children list. It's really screwy. 

![image](https://user-images.githubusercontent.com/10619135/44321439-1a2a0f80-a416-11e8-88d3-e83cb0f74676.png)

![image](https://user-images.githubusercontent.com/10619135/44321451-29a95880-a416-11e8-9658-5f6cf70001cf.png)

**Comment by jfoenixadmin** [comment] 2018-09-11 10:07
@cyberpwnn can you share your code with us? If I was able to reproduce I could fix this issue.
