### ISSUE TITLE
Using JFXTabPane causes Scene Builder to freeze

### ISSUE THREAD

**Issue by ivanskodje** [jfoenixadmin/JFoenix#234] opened 2017-01-27 06:57 UTC
Using Scene Builder 8.2.0 (Gluon) on Linux. Have tried both 32bit and 64bit.

Usually happens whenever I try to navigate in Properties/Layout/Code. It appears to be random, since it is very inconsistent about when it freezes. 
When I remove JFXTabPane it no longer freezes. Using a regular "TabPane" works as well.

Full fxml code: http://pastebin.com/3i80XR6v

If you need additional information, I am more than happy to provide them - if possible.

**Comment by eralpsahin** [comment] 2017-01-27 10:28
I could not figure out the exact problem but it is not about JFXTabPane. Scene Builder 8.3 64bit opened without any errors on Windows 10. 
<img width="771" alt="ss" src="https://cloud.githubusercontent.com/assets/10602289/22367674/eb231080-e493-11e6-8e3d-83426c63c17a.PNG">

When I tried to open in IntelliJ there was an assertion error, again don't know exactly why but the problem is inside the top tag in 52nd and 105th lines. Removing those tags fixed for IntelliJ too. You should check lines between those.

**Comment by Tybobobo** [comment] 2017-01-27 10:47
I attempted to remove <top> tags outside as specified, but the problem persists. 
Perhaps it is an Linux issue - or if you are using the default Scene Builder provided by Oracle, perhaps it is the Scene Builder itself.

**Comment by prochac** [comment] 2017-01-27 21:11
Gluon 8.3.0 works
Debian 64bit
Java Version: 1.8.0_111-b14, Oracle Corporation

**Comment by Tybobobo** [comment] 2017-01-30 12:47
I will keep working and see if I can find a cause for this.
Meanwhile, I will add information that may be relevant to this - in case I make changes that fixes the problem.

If there is any additional information that may help, please let me know and I will make sure to post it right away. :)



**Java:**

> java version "1.8.0_92"
> Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)


**Netbeans IDE 8.2:**

> Product Version: NetBeans IDE 8.2 (Build 201609300101)
> Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 1
> Java: 1.8.0_92; Java HotSpot(TM) 64-Bit Server VM 25.92-b14
> Runtime: Java(TM) SE Runtime Environment 1.8.0_92-b14
> System: Linux version 4.4.0-53-generic running on amd64; UTF-8; en_US (nb)
> User directory: /home/ivanskodje/.netbeans/8.2
> Cache directory: /home/ivanskodje/.cache/netbeans/8.2


**Scene Builder:**

> Product Version
> JavaFX Scene Builder 8.3.0
> 
> Build Information
> Version 8.3.0
> Date: 2016-12-16
> Java Version: 1.8.0_111-b14, Oracle Corporation
> 
> Logging
> The default configuration stores logging output in a file named scenebuilder-8.3.0.log (possibly followed by a trailing '.' and a digit).
> The default file path is /tmp/scenebuilder-8.3.0.log
> 
> JavaFX
> Toolkit = QuantumToolkit
> Pipeline = ES2Pipeline
> Hardware acceleration ENABLED
> 
> Java
> 1.8.0_111-b14, Oracle Corporation
> 
> Operating System
> Linux, amd64, 4.4.0-53-generic
> 
> Copyright (c) 2015-2016, Gluon.
>

**Comment by SoRRiSoJa** [comment] 2017-05-30 00:57
I Have the same problem using the JFXTabPane.
I'm  using 

Debian Jessie
Java
1.8.0_111-b14, Oracle Corporation

Operating System
Linux, amd64, 3.16.0-4-amd64

**Comment by pfdint** [comment] 2017-05-31 16:59
Same issue,

Archlinux x64
Java 1.8.0_121 OpenJDK, OpenJFX
Gluon 1.3.0
Netbeans 8.2

HOWEVER, I went to start SceneBuilder directly instead of from Netbeans. **I was able to add and work with tabs** after opening the fxml I had been working on.
Then I was able to close SceneBuilder, open it again from Netbeans, and work with the tabs normally.

Here is one of about 200 identical exceptions thrown simultaneously when working with the tabpane by editing properties in the layout inspector.
`INFO: JavaFX Scene Builder started
May 31, 2017 12:49:55 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp$SceneBuilderUncaughtExceptionHandler uncaughtException
SEVERE: An exception was thrown:
java.lang.ClassCastException: com.jfoenix.skins.JFXTabPaneSkin cannot be cast to com.sun.javafx.scene.control.skin.TabPaneSkin
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.TabPaneDesignInfoX.getContentNode(TabPaneDesignInfoX.java:95)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.TabPaneDesignInfoX.lookupTab(TabPaneDesignInfoX.java:162)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.TabPaneDriver.refinePick(TabPaneDriver.java:68)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.searchWithNode(ContentPanelController.java:534)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.pick(ContentPanelController.java:498)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.pick(ContentPanelController.java:446)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.pick(ContentPanelController.java:422)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.mouseMovedOnGlassLayer(EditModeController.java:637)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.lambda$new$2(EditModeController.java:534)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by JTMMartins** [comment] 2017-08-30 14:51
Same issue. JFX TabPane freezes Scene manager, as soon as I place it on the screen.

Ubuntu 17.04
Gnome 3.24
Gluon SceneBuilder 8.3.0

**Comment by ivanskodje** [comment] 2017-08-30 19:39
I do not know if this will affect anyone, however I have discovered I can avoid a lot of crashes that happens while working with JavaFX simply by running both the IDE and Scene Builder as administrator.

Noting this here, as it may help someone else as well :)

**Comment by RohitAwate** [comment] 2017-10-12 17:10
Running Scene Builder as administrator worked for me. Thanks!

**Comment by jfoenixadmin** [comment] 2017-10-12 17:22
will close this issue, as it should be solved from the scene builder side.

**Closed by jfoenixadmin** 2017-10-12 17:22 UTC

**Comment by magician20** [comment] 2018-11-22 10:37
Same issue. JFX TabPane freezes Scene manager, as soon as I place it on the screen.

Windows 10 64bit

Build Information
Version 8.5.0
Date: 2018-06-05
Java Version: 1.8.0_171-b11, Oracle Corporation

**Comment by Idrill7** [comment] 2019-06-05 08:55
Same issue here. 

The app version is 8.5.0 with IntelliJ Ide
Java version: jdk1.8.0_151

**Comment by MdSarfarazAlam** [comment] 2019-09-10 13:56
Run Scene builder as  Administrator and create a TabPane and Save and create again Tab inside that TabPane as many as you want !!!

**Comment by hurelhuyag** [comment] 2022-01-14 10:14
Same problem happened to me today while experimenting tabpanes. Intellij scenebuilder, gluon scenebuilder both. 
Environment: ubuntu unity7 20.04 x64, scenebuilder 17.0.0, I didn't find any specific log for it. It is annoying because entire OS half freezes. Needed to force reboot.
