### ISSUE TITLE
I can't instantiate JFXMasonryPane (JFXMasonryPane Bug?)

### ISSUE THREAD

**Issue by sajjadG** [jfoenixadmin/JFoenix#142] opened 2016-08-25 11:52 UTC
Salaam

**This code:**
```java
import com.jfoenix.controls.JFXMasonryPane;
import javafx.application.Application;
import javafx.stage.Stage;

public class MasonryTest extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {
        JFXMasonryPane jfxMasonryPane = new JFXMasonryPane();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
**Gives this error:**
```shell
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassFormatError: Method getFreeArea in class com/jfoenix/controls/JFXMasonryPane$Layout has illegal modifiers: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.jfoenix.controls.JFXMasonryPane.<init>(JFXMasonryPane.java:239)
	at io.github.sajjadg.javaplayground.MasonryTest.start(MasonryTest.java:14)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
```

**pom.xml:**
```xml
<dependency>
       <groupId>com.jfoenix</groupId>
       <artifactId>jfoenix</artifactId>
       <version>0.0.0-SNAPSHOT</version>
</dependency>
```

**JDK version:** jdk1.8.0_91
**OS:** Debian testing

Am I doing anything wrong? or this a bug?

**Comment by jfoenixadmin** [comment] 2016-08-25 12:07
please verify your java version, getFreeArea method is a default method in an interface (this is a new feature in Java 8, it's not compatible with old versions).
are you using JFoenix-retrolambda version or JFoenix-desktop version? 
can you provide more details, as we couldn't reproduce.

**Comment by sajjadG** [comment] 2016-08-25 13:03
I checked and my JDK version is `jdk1.8.0_91`.
I'm not sure about the JFoenix version I'm using. I couldn't find any official reference to maven repository and after checking the issues I found this one which I'm using:
```xml
<dependency>
       <groupId>com.jfoenix</groupId>
       <artifactId>jfoenix</artifactId>
       <version>0.0.0-SNAPSHOT</version>
</dependency>
```
I couldn't resolve some dependencies with gradle (I think my network proxy problem or something).
here is my `pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jfoenix</groupId>
    <artifactId>demo.masonry</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <repositories>
        <repository>
            <id>jfoenix</id>
            <url>https://oss.sonatype.org/content/groups/public</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.jfoenix</groupId>
            <artifactId>jfoenix</artifactId>
            <version>0.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```

And also I created an ant project and downloaded the latest (?) jar from the GitHub main page (beta version) and added it to the project but still I got the same error.

_I've cloned the source code from the github but I can't find masonryPane in demo section. There's a MasonryPane gif in the github homepage but I can't find the code in the demo package._

**Comment by jfoenixadmin** [comment] 2016-08-25 16:54
please note that his error is caused because the method getFreeArea has the "default" modifier, so most probably the cause is some class path issues related to java version in your project (from the error stack trace it indicates that it couldn't recognize the default modifier for some reason).

**Comment by sajjadG** [comment] 2016-08-27 08:35
I tested the same code in windows using `jdk1.8.0_92` and I still get the same error.

```shell
"C:\Program Files\Java\jdk1.8.0_92\bin\java" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_92\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_92\jre\lib\ext\zipfs.jar;C:\Users\windows7\Desktop\mason\MasonryPaneAnt\out\production\MasonryPaneAnt;C:\Users\windows7\Desktop\jfoenix.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain MasonryPaneDemo
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassFormatError: Method getFreeArea in class com/jfoenix/controls/JFXMasonryPane$Layout has illegal modifiers: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.jfoenix.controls.JFXMasonryPane.<init>(JFXMasonryPane.java:239)
	at MasonryPaneDemo.start(MasonryPaneDemo.java:9)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more

Process finished with exit code 1
```

**Comment by jfoenixadmin** [comment] 2016-08-27 14:33
the problem might be because you are using maven to build ur project, it enforces its own compiler and it seems that default method modifier is disabled in maven compiler. Can you try to compile ur code without using maven, or google if there is some option u need to enable in order for maven compiler to recognize the default method modifier.

**Comment by jfoenixadmin** [comment] 2016-08-27 14:34
anyway i'll close this issue, as it's not related to jfoenix.

**Closed by jfoenixadmin** 2016-08-27 14:34 UTC
