### ISSUE TITLE
Missing some components like JFXButton in my project

### ISSUE THREAD

**Issue by ExcellZeR** [jfoenixadmin/JFoenix#446] opened 2017-10-03 01:27 UTC
Hi everyone, 

I have just started using jfoenix in my project by adding the jar file in it, and I have noticed the absence of the component JFXButton from the left panel of the Scene Builder, I have also write its name in the quick search input but still no results. (Using Netbeans and Scene Builder)
Is there a problem in my configuration ?

Thank you :) !!

**Comment by jfoenixadmin** [comment] 2017-10-03 06:29
Hello,
We tested the latest JFoenix jar with scene builder, however we were not able to reproduce the issue. plz make sure to use the latest version of scene builder + jfoenix.

Regards,

**Comment by ExcellZeR** [comment] 2017-10-03 18:52
Thank you for your answer, 
I was using the Gluon version of scene builder and when I switched to the Oracle scene builder 2.0, all the components which were missing are back.
When I loaded the jar file to the Gluon version, it says that there are just 21 components available, but with the Oracle version there are 39 components.
Thank you again and I wish you all the success !!

**Comment by nirmitha-mw** [comment] 2017-10-03 19:57
Yes, I have noticed that some components are missing. In my case, there is 25 components only.

**Comment by jfoenixadmin** [comment] 2017-10-05 15:03
Hello,
it seems there is some issue with scene builder 8.4.0, according to import analysis report:
the class com.sun.javafx.css.StyleConverterImpl was not found! which is part of Java 8, however it's been refactored in Java 9. 
will close this issue as it's not related to JFoenix development.

Regards,

**Closed by jfoenixadmin** 2017-10-05 15:03 UTC
