### ISSUE TITLE
JFXDrawer open() set content mouse transparent

### ISSUE THREAD

**Issue by fgnm** [jfoenixadmin/JFoenix#397] opened 2017-08-08 13:18 UTC
Hello I'm trying to use a JFXDrawer to change the content of my main screen as like a menu. So when I set for the first time the content with drawer.setContent() everything works great. When I change content it still works but the content is disabled and anything clickable. But I can navigate and use the content with keyboard, basically just the mouse does not work anymore after changing the content

This is the code I've used:
```Java
 @Override
    public void initialize(URL url, ResourceBundle rb) {
        _this = this;
        rootP = root;

        try {
            VBox box = FXMLLoader.load(getClass().getResource("Drawer.fxml"));
            drawer.setSidePane(box);
        } catch (IOException ex) {
            Logger.getLogger(MainScene.class.getName()).log(Level.SEVERE, null, ex);
        }

        mMenuIconAnimation = new HamburgerBackArrowBasicTransition(hamburger);
        mMenuIconAnimation.setRate(-1);
        hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e) -> {
            mMenuIconAnimation.setRate(mMenuIconAnimation.getRate() * -1);
            mMenuIconAnimation.play();

            if (drawer.isShown()) {
                drawer.close();
            } else {
                drawer.open();
            }
        });

        try {
            mTableScene = FXMLLoader.load(getClass().getResource("TableScene.fxml"));
            mTableScene2 = FXMLLoader.load(getClass().getResource("TableScene_1.fxml"));
        } catch (IOException ex) {
            Logger.getLogger(MainScene.class.getName()).log(Level.SEVERE, null, ex);
        }

        setContent(TABLE_NODE, false); //First call works, others set the content but disabled and no clickable
    }

    //Here is the problem!
    public void setContent(int index, boolean animation) {
        
        switch (index) {
            case TABLE_NODE:
                drawer.setContent(mTableScene);
                break;
            case TABLE2_NODE:
                drawer.setContent(mTableScene2);
                break;
        }
        drawer.close();
        if (animation) {
            mMenuIconAnimation.setRate(mMenuIconAnimation.getRate() * -1);
            mMenuIconAnimation.play();
        }
    }
```

**EDIT**
I've found the key of the problem, every time I open JFXDrawer (drawer.open();) the content become mouse transparent, any solution?

A possible solution is to disable overlay ``` drawer.setOverLayVisible(false); ``` but we lost nice effect

**Comment by jfoenixadmin** [comment] 2017-08-11 19:31
Hello,
We were not able to reproduce the issue, JFXDrawer doesn't set its content to be mouse transparent.

- Opening JFXDrawer will trigger the overlay to be on top of the content and its mouse transparent property is set to false, thus it will prevent any mouse event to be passed to the content.
- Closing the drawer will revert this, it will hide the overlay and set its mouse transparent property to true.

if you can provide a full example demonstrating the issue, we might be able to help.

Regards,

**Closed** 2017-08-24 17:35 UTC
