### ISSUE TITLE
jfx-text-field design like gmail login

### ISSUE THREAD

**Issue by Vimptech** [jfoenixadmin/JFoenix#1023] opened 2019-07-01 10:06 UTC
jfx-text-field css for design like gmail login
![Screenshot from 2019-07-01 15-34-25](https://user-images.githubusercontent.com/52407123/60428214-fe86bc80-9c15-11e9-8e27-49f1e148bd67.png)

**Comment by skmedix** [comment] 2019-07-13 13:24
Duplicate of #912

**Closed by skmedix** 2019-07-13 13:24 UTC
Labels: Type: Feature
