### ISSUE TITLE
Multiple lines of text bug

### ISSUE THREAD

**Issue by koy-tome** [jfoenixadmin/JFoenix#482] opened 2017-10-31 01:13 UTC
Multi line text box. When a vertical scroll bar appears, you cannot select a text that is beyond its proper size. The mouse scroll is not valid in the text field.

![_20171031091134](https://user-images.githubusercontent.com/24954758/32202985-7e260dd6-be1b-11e7-99fb-a5718cc4f693.png)

**Comment by jfoenixadmin** [comment] 2017-10-31 07:54
Hello,
Can you provide a sample example demonstrating the issue?

**Comment by koy-tome** [comment] 2017-11-01 02:49
I put a JFXTextArea in the FXML file, enter the text in the picture, I would like to select j / k / l three lines, but the selected line did go to h / i where the line went. You can try. THX.

**Comment by jfoenixadmin** [comment] 2017-11-02 12:55
Hello,
we were not able to reproduce the issue, if you can provide a full example demonstrating the issue it would be appreciated. else will close this issue.

Regards,

**Comment by koy-tome** [comment] 2017-11-03 06:17
Open the JavaFX Scene Builder 2.0

**Comment by koy-tome** [comment] 2017-11-03 06:17
test

**Comment by koy-tome** [comment] 2017-11-03 06:19
[test.zip](https://github.com/jfoenixadmin/JFoenix/files/1440198/test.zip)Using JavaFX Scene Builder 2 open

**Comment by jfoenixadmin** [comment] 2017-11-06 05:45
still not able reproduce, the selection is fine.

**Closed** 2017-11-14 07:20 UTC
