### ISSUE TITLE
How can I have a behavior with JFXDialog or other like Alert (FX)

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#165] opened 2016-09-30 15:11 UTC
Hi ! 
I don't understand something.
If I'm in the "for loop" for this case. 
The following code do exactly that I want, but it's not material design:
```
 Alert alert = new Alert(AlertType.CONFIRMATION);
              alert.setTitle("Confirmation Dialog with Custom Actions");
              alert.setHeaderText("Do you want rename it ?");
              alert.setContentText("Before : ");
              alert.getDialogPane().getStylesheets().add(
              getClass().getResource("/resources/css/jfoenix-main-demo.css").toExternalForm());
              alert.getDialogPane().getStyleClass().add("myDialog");

              ButtonType buttonYes = new ButtonType("YES");
              ButtonType buttonNo = new ButtonType("NO", ButtonData.CANCEL_CLOSE);
              ButtonType buttonYesAll = new ButtonType("YES ALL");
              ButtonType buttonNoAll = new ButtonType("NO ALL");

              alert.getButtonTypes().setAll(buttonYes, buttonNo, buttonYesAll, buttonNoAll);

```
Each time, I have one only  popup which wait at my answer. 
 
I tried to make again this window like this:
It's not a JFXDialog here but I have the same result with this code.
I don't know if I have to do all from Scratch or use something which already exist.

```
<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXButton?>
<?import javafx.geometry.Insets?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.image.ImageView?>
<?import javafx.scene.layout.ColumnConstraints?>
<?import javafx.scene.layout.GridPane?>
<?import javafx.scene.layout.HBox?>
<?import javafx.scene.layout.Pane?>
<?import javafx.scene.layout.RowConstraints?>
<?import javafx.scene.layout.VBox?>
<?import javafx.scene.text.Font?>

<GridPane fx:id="gridPopup" hgap="14.0" maxHeight="+Infinity" maxWidth="+Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="181.0" prefWidth="437.0" vgap="20.0" xmlns="http://javafx.com/javafx/8.0.60" xmlns:fx="http://javafx.com/fxml/1">
  <children>
    <ImageView fx:id="logoPopupRename" fitHeight="60.0" fitWidth="60.0" pickOnBounds="true" preserveRatio="true" GridPane.columnIndex="0" GridPane.halignment="CENTER" GridPane.rowIndex="0" GridPane.valignment="TOP">
      <image>
        <!-- place holder -->
      </image>
    </ImageView>
    <VBox maxHeight="+Infinity" maxWidth="+Infinity" minHeight="-Infinity" prefWidth="400.0" spacing="7.0" GridPane.columnIndex="1" GridPane.rowIndex="0">
      <children>
        <Label fx:id="messageLabelRenamePopup" text="Do you want to rename ?" textAlignment="LEFT" wrapText="true">
          <font>
            <Font name="System Bold" size="13.0" />
          </font>
        </Label>
        <Label fx:id="detailsBeforeLabelPopupRename" prefHeight="35.0" prefWidth="411.0" text="Before: " textAlignment="LEFT" underline="false" wrapText="true">
          <font>
            <Font size="12.0" />
          </font>
        </Label>
            <Label fx:id="detailsAfterLabelPopupRename" prefHeight="35.0" prefWidth="401.0" text="After:" textAlignment="LEFT" underline="false" wrapText="true">
               <font>
                  <Font size="12.0" />
               </font>
            </Label>
      </children>
    </VBox>
    <HBox maxHeight="-Infinity" maxWidth="+Infinity" minHeight="-Infinity" minWidth="-Infinity" GridPane.columnIndex="1" GridPane.rowIndex="1">
      <children>
        <HBox fx:id="actionParent" alignment="CENTER">
          <HBox.margin>
            <Insets />
          </HBox.margin>
        </HBox>
        <Pane maxWidth="+Infinity" HBox.hgrow="ALWAYS" />
        <HBox fx:id="okParent" prefHeight="30.0" prefWidth="428.0" spacing="10.0">
               <children>
                  <JFXButton fx:id="buttonYesPopupRename" buttonType="RAISED" onAction="#onYesButton" prefHeight="30.0" prefWidth="74.0" style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;" text="Yes" />
                  <JFXButton fx:id="buttonNoPopupRename" buttonType="RAISED" onAction="#onNoButton" prefHeight="25.0" prefWidth="69.0" style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;" text="No" />
                  <JFXButton fx:id="buttonYesAllPopupRename" buttonType="RAISED" onAction="#onYesAllButton" prefHeight="25.0" prefWidth="70.0" style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;" text="Yes All" />
                  <JFXButton fx:id="buttonNoAllPopupRename" buttonType="RAISED" maxWidth="79.0" minWidth="75.0" onAction="#onNoAllButton" prefHeight="25.0" prefWidth="79.0" style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;" text="No All" />
               </children>
        </HBox>
      </children>
    </HBox>
  </children>
  <columnConstraints>
    <ColumnConstraints hgrow="NEVER" maxWidth="57.0" minWidth="-Infinity" prefWidth="24.0" />
    <ColumnConstraints halignment="CENTER" hgrow="ALWAYS" maxWidth="Infinity" minWidth="-Infinity" prefWidth="436.0" />
  </columnConstraints>
  <padding>
    <Insets bottom="14.0" left="14.0" right="14.0" top="14.0" />
  </padding>
  <rowConstraints>
    <RowConstraints maxHeight="Infinity" minHeight="-Infinity" prefHeight="108.0" valignment="CENTER" vgrow="ALWAYS" />
    <RowConstraints maxHeight="25.0" minHeight="-Infinity" prefHeight="25.0" vgrow="NEVER" />
  </rowConstraints>
</GridPane>

```

But How to have a modal window which don't create an other one behind the first. I want only one popup by one and not all in the same time even if others aren't activate ? What element have I to use ? JFXDialog ? Or any ? 

Look at this picture:
![image](https://cloud.githubusercontent.com/assets/6093175/18996261/e7de44d8-872f-11e6-90d8-269ca4d628d8.png)

![image](https://cloud.githubusercontent.com/assets/6093175/19019898/8f76c36a-8897-11e6-8892-140c9c6144f2.png)

I don't know if it's me or an other problem more specific to the JFX components.

Thanks to light me at this subject

**Comment by jfoenixadmin** [comment] 2016-10-03 07:01
well JFXDialog is different from Alert, JFXDialog opens the dialog inside a certain parent Node (by default it's the root) in your current stage.

to make your stage modal what you need to do is to call the following on your popup stage:
`popupStage.initModality(Modality.APPLICATION_MODAL);`

**Comment by kevincaradant** [comment] 2016-10-03 20:30
Mhh yes but look this. I refound it in JAVA without Stage and Scene because I want it in the same Stage, it's more usefull in my case. 

This is my code:

```
private void createPopup () throws FlowException{
	  	JFXDialog dialog = new JFXDialog(root, content, JFXDialog.DialogTransition.CENTER);
	  	dialog.setOverlayClose(false);
   		content.setHeading(new Text("Do you want to rename ?"));
   		GridPane  root = new GridPane ();
   		root.setId("gridPopup");
   		root.setPrefHeight(181);
   		root.setPrefWidth(437);
   		root.setVgap(20);
   		root.setHgap(14);
   		
   		
   		
   		VBox vbox = new VBox();
   		vbox.setPrefWidth(400);
   		vbox.setSpacing(7);
   		
   		Label detailsAfterLabelPopupRename = new Label("Before: "+film.getNameWithoutExt());
   		detailsAfterLabelPopupRename.setId("messageLabelRenamePopup");
   		detailsAfterLabelPopupRename.setFont(new Font("System Bold", 12));
   		
   		Label detailsBeforeLabelPopupRename = new Label("After: "+film.getCleanName());
   		detailsBeforeLabelPopupRename.setId("detailsBeforeLabelPopupRename");
   		detailsBeforeLabelPopupRename.setFont(new Font("System Bold", 12));
   		
   		vbox.getChildren().addAll(detailsBeforeLabelPopupRename, detailsAfterLabelPopupRename);
   		
   		HBox actionParent = new HBox();
   		actionParent.setId("actionParent");
   		actionParent.setAlignment(Pos.CENTER);
   		
   		HBox okParent = new HBox();
   		okParent.setId("okParent");
   		okParent.setSpacing(10);
   		okParent.setAlignment(Pos.CENTER);
   		
   		
   		JFXButton buttonYesPopupRename = new JFXButton("Yes");
   		buttonYesPopupRename.setPrefHeight(30);
   		buttonYesPopupRename.setPrefWidth(70);
   		buttonYesPopupRename.setId("buttonYesPopupRename");
   		buttonYesPopupRename.setButtonType(ButtonType.RAISED);
   		buttonYesPopupRename.setOnAction(e -> {film.applyRename(film.getCleanName()); dialog.close();});
   		buttonYesPopupRename.setStyle("-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;");
   		
   		JFXButton buttonNoPopupRename = new JFXButton("No");
   		buttonNoPopupRename.setPrefHeight(30);
   		buttonNoPopupRename.setPrefWidth(70);
   		buttonNoPopupRename.setId("buttonNoPopupRename");
   		buttonNoPopupRename.setButtonType(ButtonType.RAISED);
   		buttonNoPopupRename.setOnAction(e -> dialog.close());
   		buttonNoPopupRename.setStyle("-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;");
   		
   		
   		JFXButton buttonYesAllPopupRename = new JFXButton("Yes All");
   		buttonYesAllPopupRename.setPrefHeight(30);
   		buttonYesAllPopupRename.setPrefWidth(70);
   		buttonYesAllPopupRename.setId("buttonYesAllPopupRename");
   		buttonYesAllPopupRename.setButtonType(ButtonType.RAISED);
   		buttonYesAllPopupRename.setOnAction(e-> yesAll = true);
   		buttonYesAllPopupRename.setStyle("-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;");
   		
   		
   		JFXButton buttonNoAllPopupRename = new JFXButton("No All");
   		buttonNoAllPopupRename.setPrefHeight(30);
   		buttonNoAllPopupRename.setPrefWidth(70);
   		buttonNoAllPopupRename.setId("buttonNoAllPopupRename");
   		buttonNoAllPopupRename.setOnAction(e -> noAll = true);
   		buttonNoAllPopupRename.setButtonType(ButtonType.RAISED);
   		buttonNoAllPopupRename.setStyle("-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;");
   		
   		
   		
   		okParent.getChildren().addAll(buttonNoAllPopupRename, buttonYesAllPopupRename, buttonNoPopupRename, buttonYesPopupRename);
   		
   		GridPane.setColumnIndex(okParent, 1);
   		GridPane.setRowIndex(okParent, 1);
   		GridPane.setColumnIndex(vbox, 1);
   		GridPane.setRowIndex(vbox, 0);
   		root.getChildren().addAll(vbox, okParent);
   		content.setBody(root);
   		dialog.show();
  }
```

And the problem is my sidebar on left. I can click on it during the active popup :/. I don't know how can I have a modal application where only JFXDialog is active and the rest are not knowning that JFXDialog uses the main Stage ( only one).

Little topic off but I would be very happy if you know the answer because I didn't find it on Google:
I don't understand how can I pass a new value for a variable to the parent. 
I do set a context in the parent node. 
flowContext.register("Settings", settings);
And in the child, I get this value like this:
`Settings settings = (Settings) context.getRegisteredObject("Settings");`
But if I edit the settings in the child (settings are edited only for the child object like if it's a copy of the parent object), how can I say at the parents, OK now the settings it's this because the child has edited settings. Thank you very much :)

**Comment by jfoenixadmin** [comment] 2016-10-04 06:51
Hello, 

it seems that you are passing content of drawer as the JFXDialog container, what you need to do is to pass the root of your scene (instead of the drawer content node), you can either pass it in constructor or by calling the method:

`dialog.setDialogContainer(sceneRoot);`

and regarding the Settings issue, i tested the scenario you mentioned but was not able to reproduce, it's working fine. if you changed a value of the settings it gets change in the parent.

however in case you are creating a new settings in the child instead of editing the same object, then you need to register it in the context again in order for it to be accessible in the parent.

Regards,

**Comment by kevincaradant** [comment] 2016-10-04 16:14
Hi

Sorry but I don't successful, so I know it's not easy to you. I prepared a repo of my app here:
https://github.com/kevincaradant/maxiFilm.git

git checkout dev

In this repo:
Look at HomeController.java / PopupOthrt.java and eventually SideMenu.java.
You have all my examples and problems prepared here for you.
Thank you very much I hope you will unblock me on a lot of things :)

PS: I use 'context' because I don't know pass arguments at the FXML classes when I do:
Flow flow2 = new Flow(PopupOthrt.class);

**Comment by jfoenixadmin** [comment] 2016-10-05 07:03
to solve your popup modality issue, you need to do the following (as mentioned before)
you need to register the root in your MainController in the context:

`context.register("ROOT", root);`

then use this root as the JFXDialog container in HomeController:

`JFXDialog dialog = new JFXDialog((StackPane) context.getRegisteredObject("ROOT"), content, JFXDialog.DialogTransition.CENTER);`

**Comment by kevincaradant** [comment] 2016-10-05 18:55
Yes Indeed. You talk about the example 1 in HomeController isn't ? I applied your answer, thanks. I fall on the other problem. dialog has only show() method. And when you put 2/3 files, it don't wait the answer of the first and show you only the choice for the last file. I need something like showAndWait() method or a way to set the` Modality.APPLICATION_MODAL` somewhere ?

**Comment by jfoenixadmin** [comment] 2016-10-06 08:58
you can use the method dialog.setOverlayClose(false) to prevent closing the dialog without clicking one of the dialog action buttons. 

regarding your dataFX issue, plz feel free to contact the dataFX team regarding this issue.
from a quick glance, a recommendation would be to encapsulate your value in object and use it (e.g use SimpleBooleanProperty  instead of Boolean ) so you only need to register it once, retrieve it and change its value later.

Regards,

**Comment by kevincaradant** [comment] 2016-10-06 11:16
> you can use the method dialog.setOverlayClose(false) to prevent closing the dialog without clicking one of the dialog action buttons.
I tried also, in my git example, there is this option activated in the Example1.
That's seems does not work :/. If my memory is  good, I do dialog.close() but the grey background overlay stays, something like that AND I have only one popup which appears even if I drag/drop more 1 file. 

For the second question, do you think it's an issue from dataFX ? I thought that was me which doesn't understand something. I will try tonight after work your solution with BooleanProperty. I didn't know this object. 
Thanks

**Comment by jfoenixadmin** [comment] 2016-10-07 07:01
I recommend that when you drag mutliple files you show a different popup , a one that shows a list of files to be renamed, as creating one popup for each file is bad design behavior.

btw there  is no issue regarding the overlay, it gets removed when you close the JFXdialog.

Regards,

**Comment by kevincaradant** [comment] 2016-10-07 07:25
Thanks for your advice about popup :)

For the overlay issue, tonight I will push on the git  repository a case where I have the problem, sorry I can't before. I think, it's already the case with my push of yesterday. If you uncomment all the example 1 (JFXDialog) and comment the example 2 (example with FXML File) in HomeController and then you drag/drop files 2 files and then you click on noButton or noAllButton, i don't remember the button which do the bug, all the main interface has a overlay enabled.
That's weird if you don't have any issue about it. I will try to reproduce the bug

**Comment by jfoenixadmin** [comment] 2016-10-10 07:50
the problem is caused because you are creating multiple JFXDialog using the same JFXDialogLayout object, 
to fix this you need to create JFXDialogLayout for each JFXDialog , or create one JFXDialog only as you only have one JFXDialogLayout object in your code.

**Comment by kevincaradant** [comment] 2016-10-10 07:56
> the problem is caused because you are creating multiple JFXDialog using the same JFXDialogLayout object ( you are using the same content object for each JFXDialog which is wrong ), to fix this you need to create JFXDialogLayout for each JFXDialog , or create one JFXDialog only as you only have one JFXDialogLayout object in your code.

OK, just to be clear, this answer concerns the problem about the overlay or the JFX modal ? 
I will try as soon as possible your solution :). Thank you

**Comment by jfoenixadmin** [comment] 2016-10-10 08:07
it's the cause of both

**Comment by kevincaradant** [comment] 2016-10-10 20:31
Yes OK. We are close but now I have 3 popups (3 files) but they are all superposed :/. Even if it's modal, it's not one popup created and when I said "dialog.close()", that create the second popup etc. In fact, they are all created in the for loop and I see them when I close the first then the second . I hope I'm clear :/

**Comment by jfoenixadmin** [comment] 2016-10-11 06:53
please note that this behavior is due to your implementation, what you can do is to show one JFXDialog but  customize its content to handle multiple files or keep track of the "noAll" button action and don't allow creating other dialogs if clicked.

I'm closing this issue as its no longer related to JFoenix development / use.

Regards,

**Closed by jfoenixadmin** 2016-10-11 06:53 UTC

**Comment by kevincaradant** [comment] 2016-10-11 06:59
OK I understand. Thanks for all this explications.

**Comment by Sha-litha** [comment] 2018-06-25 09:07
cant i crate a JFXDialog using only scene builder ???without using javacode ??when i tried dialogbox nodes are not visible..i created a jfxdialogbox with a dialog layout inside it..and dynmically crated a stack pane and added that precreated dialogbox to that stack pane using javacode....can someone help me
