### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by zeoliveirajunior** [jfoenixadmin/JFoenix#334] opened 2017-05-29 23:47 UTC
Hello!

I have a simple application made in Javafx using Jfoenix. The problem is a little memory leak in my components that i made extending jfoenix. I could check the objects with problem with jvisualvm , and the references are hold by the transactions and animations class used by jfoenix.

If i use the javafx normal components in the same aplication, the problem doesn´t exists.

I try update the jar to the last version, but the problem still persists.

Can i know if it is a known issue or if maybe i am doing something wrong?

**Comment by jfoenixadmin** [comment] 2017-05-30 08:26
Hello,
It's not a known issue , can you please provide more details and a sample demo if possible? 

Regards,

**Comment by jfoenixadmin** [comment] 2017-06-08 06:47
will close this issue as it seems it's caused by your own custom controls not default JFoenix controls.

Regards,

**Closed by jfoenixadmin** 2017-06-08 06:47 UTC
