### ISSUE TITLE
Closable tabs do not have button to close them

### ISSUE THREAD

**Issue by forstay** [jfoenixadmin/JFoenix#364] opened 2017-07-10 16:28 UTC
No X button to close tab in JFXTabPane.
EDIT: middle mouse button doesn't close the tab either.

![unknown](https://user-images.githubusercontent.com/28757970/28028624-7452f804-659d-11e7-9a30-ef28778a9986.png)

JFoenix version 1.6.0
Windows 7 x64

**Comment by skmedix** [comment] 2017-07-10 17:27
Duplicate of https://github.com/jfoenixadmin/JFoenix/issues/75

**Comment by forstay** [comment] 2017-07-10 17:38
No, author said that issue #75 is solved in #241. However in my case it's not working. Remove dublicate.

**Comment by forstay** [comment] 2017-07-10 17:40
No, author said that issue #75 is solved in 5955fdf. However in my case it's not working.

**Comment by skmedix** [comment] 2017-07-10 17:51
https://github.com/jfoenixadmin/JFoenix/pull/241 including https://github.com/jfoenixadmin/JFoenix/commit/5955fdfa71ad377a3c0f3d83c8ca9af9a9f78e4d wasn't merged.

**Comment by jfoenixadmin** [comment] 2017-07-11 06:44
well this issue is not resolved yet in master branch, this issue is more of a design issue.
We need a material design behavior to integrate the close button in JFXTabPane, otherwise it feels off in the header.

Feel free to suggest any design for this issue and contribute to JFonenix.

Regards,

**Comment by jfoenixadmin** [comment] 2017-07-11 06:48
Hello,
well

**Closed by jfoenixadmin** 2017-07-11 06:48 UTC
Labels: enhancement

**Comment by Otasy** [comment] 2018-09-11 08:56
Hello,
how to change color of close button?
