### ISSUE TITLE
JFXCombobox was broken by commit d5a2a7bc87d8e91fd22e19cedd97b199fff48bf5

### ISSUE THREAD

**Issue by RGamberini** [jfoenixadmin/JFoenix#29] opened 2015-12-16 23:11 UTC
Choosing an item from JFXCombobox now causes a RunTimeException.

This bug is reproducible using the official demo app.

Stack trace:
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: .pre
fWidth : A bound value cannot be set.
        at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:
143)
        at javafx.css.StyleableDoubleProperty.set(StyleableDoubleProperty.java:8
2)
        at javafx.scene.layout.Region.setPrefWidth(Region.java:1076)
        at javafx.scene.layout.Region.setPrefSize(Region.java:1121)
        at com.sun.javafx.scene.control.skin.ComboBoxPopupControl.reconfigurePop
up(ComboBoxPopupControl.java:318)
        at com.sun.javafx.scene.control.skin.ComboBoxListViewSkin.computeMinHeig
ht(ComboBoxListViewSkin.java:257)
        at javafx.scene.control.Control.computeMinHeight(Control.java:487)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.VBox.getAreaHeights(VBox.java:436)
        at javafx.scene.layout.VBox.computeContentHeight(VBox.java:518)
        at javafx.scene.layout.VBox.computeMinHeight(VBox.java:396)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1960)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1847)
        at javafx.scene.layout.HBox.computeMinHeight(HBox.java:415)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Reva:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.BorderPane.getAreaHeight(BorderPane.java:618)
        at javafx.scene.layout.BorderPane.computeMinHeight(BorderPane.java:415)
        at javafx.scene.Parent.minHeight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697
)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
        at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
        at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
        at javafx.scene.Parenight(Parent.java:949)
        at javafx.scene.layout.Region.minHeight(Region.java:1401)
        at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:176
2)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1979)
        at javafx.scene.layout.Region.computeMaxPrefAreaHeight(Region.java:1881)

        at javafx.scene.layout.StackPane.computePrefHeight(StackPane.java:306)
        at javafx.scene.Parent.prefHeight(Parent.java:921)
        at javafx.scene.layout.Region.prefHeight(Region.java:1435)
        at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:176
2)
        at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1979)
        at javafx.scene.layout.Region.computeMaxPrefAreaHeight(Region.java:1881)

        at javafx.scene.layout.StackPane.computePrefHeight(StackPane.java:306)
        at javafx.scene.Parent.prefHeight(Parent.java:921)
        at javafx.scene.layout.Region.prefHeight(Region.java:1435)
        at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:176
2)
        at javafx.scene.layout.VBox.getAreaHeights(VBox.java:440)
        at javafx.scene.layout.VBox.layoutChildren(VBox.java:555)
        at javafx.scene.Parent.layout(Parent.java:1079)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$31(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:51
0)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:49
0)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$405(Quantu
mToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatch
er.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.ja
va:191)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jfoenixadmin** [comment] 2015-12-17 08:40
the issue is related to creating JFXListCell, it's fixed now.
Thanks for pointing out the issue.

**Closed by jfoenixadmin** 2015-12-17 08:40 UTC
